-- Project Export Information
-- Generated by Roblox Script Exporter

return {
    sourceFile = ".\Obbyincrevasse.rbxl",
    exportDate = "2026-03-29 12:06:43",
    luneVersion = "0.9.3",
    structure = "Service-based organization with nested script support",
    notes = {
        "Server scripts have .server.lua extension",
        "Client scripts have .client.lua extension",
        "Module scripts have .lua extension",
        "Nested scripts are placed in '_contents' folders",
        "Scripts inside scripts are marked as NESTED in headers",
        "Metadata preserved in file headers",
        "Empty '_contents' folders are not created"
    }
}